name: PyInstaller Build

on:
  push:
    branches:
      - release

jobs:
  build-linux:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      DISPLAY: ':99.0'
    
    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"  # Adjust the version as needed

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y qt6-base-dev qt6-multimedia-dev
          /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # Step 4: Build with PyInstaller
      - name: Build Executable
        run: |
          pyinstaller --onefile src/main.py

      # Step 5: Archive the build artifacts
      - name: Archive Build
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: dist/
